use_frameworks!

platform :ios, '13.0'

target 'SwiftLoadingSpinner_Example' do
  pod 'SwiftLoadingSpinner', :path => '../'

  target 'SwiftLoadingSpinner_Tests' do
    inherit! :search_paths

    
  end
end
